version: "3.8"

services:
  postgres:
    image: postgres:15-alpine # 使用輕量的 Alpine 版本
    container_name: neng-shop-postgres
    restart: unless-stopped
    environment:
      # 這些環境變數會設定 PostgreSQL 的初始使用者和資料庫
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: neng_shop
      # 設定時區
      TZ: Asia/Taipei
    ports:
      - "5432:5432" # 對外開放 5432 port
    volumes:
      # 資料持久化：即使容器刪除，資料也不會消失
      - postgres_data:/var/lib/postgresql/data
      # 可選：初始化腳本資料夾
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      # 健康檢查：確保資料庫真的準備好了
      test: ["CMD-SHELL", "pg_isready -U myusername -d neng_shop"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin（資料庫管理工具的網頁版）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: neng-shop-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

# 定義資料卷，確保資料持久化
volumes:
  postgres_data:
